spring:
  profiles:
    active: dev  # 默认激活开发环境，线上通过启动参数 -Dspring.profiles.active=prd 覆盖

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8090
  servlet:
    context-path: /api
    session:
      timeout: 7200s # 会话超时时间2小时
