# 线上生产环境配置（此文件包含敏感信息，不应提交到Git）
spring:
  datasource:
    url: jdbc:mysql://rm-bp16nj63444qf3v96.mysql.rds.aliyuncs.com:3306/management_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Wangyang@7
